### ISSUE TITLE
Vincular páginas

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-04#12]
Sería bueno si ya vincularan los links a las páginas a las cuales apuntan.

https://github.com/0623CIFSNCN05LAED/grupo-04/blob/9c55c54773e0a29b31da46232b306fdc5ed611de/src/views/partials/header.ejs#L30-L31

**Comment by nadiiasoria** [comment]
Ya vinculamos algunos link y nos falta completar información para linkear la parte sobre "nosotros"
