### ISSUE TITLE
Usar rutas absolutas

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-04#13]
Recuerden siempre usar rutas absolutas en vez de relativas. Debería comenzar directo con / (que es nuestra carpeta public)

https://github.com/0623CIFSNCN05LAED/grupo-04/blob/9c55c54773e0a29b31da46232b306fdc5ed611de/src/views/productCart.ejs#L76-L78

**Comment by nadiiasoria** [comment]
Ya pasamos a rutas absolutas
