### ISSUE TITLE
Implementación de nodemon

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-04#15]
Se les sugiere ampliamente que implementen `nodemon` en su proyecto siendo que, a partir de este punto, tendrán mucho cambio en los archivos JavaScript, cosa que requerirá de un reinicio del servidor luego de cada uno.
https://github.com/0623CIFSNCN05LAED/grupo-04/blob/9c55c54773e0a29b31da46232b306fdc5ed611de/package.json#L6-L9

**Comment by nadiiasoria** [comment]
ya instalamos nodemon
